name: Waifu Generator Scheduling

on:
  push:
    branches: master
  
  schedule:
    - cron: '*/5 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
    - run: yarn install
    - name: Scrape data
    - run: yarn dev
      
    - name: Commit the data scrape
      run: |
        git config --local user.email "satyawikananda456@gmail.com"
        git config --local user.name "satyawikananda"
        git add -A
        git commit -m ":zap: Update data scrape"
        
    - name: Github push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
